language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
  - covr
  - devtools

r_github_packages:
  - codecov/example-r

jobs:
  include:
  - r: devel
  - os: osx
  - r: release
  - r: 4.0
  - r: 3.6
  - r: 3.5


