# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix multiplication between two matrices
#'
#' @param Mat1 a matrix.
#' @param Mat2 another matrix.
#' @return prod the product Mat1%*%Mat2
#' @export
'%mult%' <- function(Mat1, Mat2) {
    .Call('_survPen_multmat', PACKAGE = 'survPen', Mat1, Mat2)
}

#' Matrix multiplication between a matrix and a vector
#'
#' @param Mat a matrix.
#' @param vec a vector.
#' @return prod the product Mat%*%vec
#' @export
'%vec%' <- function(Mat, vec) {
    .Call('_survPen_multvec', PACKAGE = 'survPen', Mat, vec)
}

